### ISSUE TITLE
missing reference field in the CreateAndSendInvoice function

### ISSUE THREAD

**Issue by kidd0203** [paypal/invoice-sdk-dotnet#5]
the reference field is missing in the CreateAndSendInvoice function.
There is a reference field in the REST Invoicing API ->
https://developer.paypal.com/docs/api/invoicing/#invoices_create

**Comment by bluk** [comment]
It is unlikely that the field will be added to the [SOAP/NVP Invoicing API](https://developer.paypal.com/docs/classic/api/#invoicing). I suggest you use the [REST API SDK](https://github.com/paypal/PayPal-NET-SDK) for that functionality if possible.
