### ISSUE TITLE
Configurable authentication headers required

### ISSUE THREAD

**Issue by fcrocker** [paypal/invoice-sdk-dotnet#6]
As defined in https://developer.paypal.com/webapps/developer/docs/api/#authentication--headers, there might be needed additional headers, like partner BN code (key "PayPal-Partner-Attribution-Id").

The .NET Core SDK supports the adding of custom HTTP Headers through configuring the apiContext Object:
https://github.com/paypal/PayPal-NET-SDK/wiki/Make-Your-First-Call

Is there any way to have similar functionality with this SDK?

**Comment by pp-randy** [comment]
Have you looked into the referredCode field? 
 https://developer.paypal.com/docs/classic/api/invoicing/CreateInvoice_API_Operation/
![image](https://cloud.githubusercontent.com/assets/6819909/22830830/99862296-ef6d-11e6-94de-98e20571576a.png)


https://github.com/paypal/invoice-sdk-dotnet/blob/2fc808c05600e7fab6318791b207f54c31a7e479/PayPalInvoiceSDK/Invoice/PayPalInvoiceModel.cs#L2361

**Comment by pp-randy** [comment]
Closing the issue, please let me know if you need further assistance.
